Rewrite ci/cd from travis to GitHub actions
vazco/sparrowql pull request #31
Opened 2023-07-07 10:43 UTC by ErnestTeluk

Rewrite ci/cd from Travis to GitHub actions.

2023-07-07 12:12 UTC, radekmie requested changes
Two small things:
1. It's only "CI" as we don't deploy anything. (And it's "CI", not "ci" 😛)
2. Can we name the actions accordingly? Like, instead of "16.x, 6" have "Node.js 16.x, MongoDB 6.0". (It may be a good idea to encode versions as strings to `6.0` stays as `6.0` and not `6`).

2023-07-12 11:46 UTC, radekmie commented on .github/workflows/CI.yml
> +        mongodb-version: [3.6, 4.0, 4.2, 4.4, 6.0]
```suggestion
        mongodb-version: [3.6, '4.0', 4.2, 4.4, '6.0']
```

2023-07-13 09:18 UTC, radekmie approved these changes

2023-07-17 08:10 UTC, zendranm approved these changes

2023-07-21 10:03 UTC, merged